---
# afs cell name
afs_cell: example.com

# kerberos realm name
afs_realm: EXAMPLE.COM

# Kerberos and AFS admin principal
afs_admin_principal: admin

# Kerberos and AFS admin password (no default)
# afs_admin_password:

# Initial password of created principals.
# See afs_users below. (no default)
# afs_user_password

# primary kerberos kdc hostname
afs_kdc: "{{ groups['afs_kdcs'][0] }}"

# primary fileserver hostname
afs_root_server: "{{ groups['afs_fileservers'][0] }}"

# primary fileserver afs partition id
afs_root_part: a

# afsd options
# TODO: should detect or get this from the client role.
afs_afsd_opts: -dynroot -fakestat -afsdb

# Initial top level volumes.
#
#     afs_volumes:
#       - name: volume_one
#       - name: volume_two
#         mtpt: test
#
afs_volumes: []

# Initial AFS users.
#
#     afs_users:
#       - name: user1
#       - name: user2
#
afs_users: []

# Initial AFS groups.
#
#    afs_groups:
#      - name: group1
#        members:
#          - user1
#          - user2
#
afs_groups: []
