---
galaxy_info:
  namespace: openafs_contrib
  role_name: openafs_krbserver
  author: Michael Meffie
  description: Kerberos server
  company: Sine Nomine Associates
  license: license (BSD)
  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - jessie
        - stretch
        - buster

  galaxy_tags:
    - system
    - openafs

dependencies: []
