---
- name: "CentOS-6: Trace repo url"
  debug:
    var: afs_client_repo_url

- name: "CentOS-6: Add OpenAFS yum repo"
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_client_repo_url }}"
    gpgcheck: no

- name: "CentOS-6: DKMS mode"
  when: afs_client_install_dkms | bool
  block:
    - name: "CentOS-6: Add epel yum repo"
      become: yes
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: "CentOS-6: Install OpenAFS client with DKMS"
      yum:
        state: present
        name:
          - openafs
          - openafs-client
          - dkms-openafs
          - openafs-krb5
      register: yum_results

    - name: "CentOS-6: Get dkms status"
      command: dkms status
      check_mode: no
      changed_when: false
      register: dkms_status

    - debug:
        var: dkms_status
        verbosity: 1

    - name: "CentOS-6: Verify openafs dkms status is 'installed'"
      assert:
        that:
          dkms_status.stdout is regex('openafs, .* installed')

- name: "CentOS-6: kmod mode"
  when: not (afs_client_install_dkms | bool)
  block:
    - name: "CentOS-6: Install OpenAFS base package"
      yum:
        state: present
        name:
          - openafs

    - name: "CentOS-6: Query OpenAFS version"
      command: rpm -q --queryformat "%{VERSION}" openafs
      args:
        warn: False
      changed_when: False
      register: rpm_query

    - name: "CentOS-6: Set kernel module package version"
      set_fact:
        afs_openafs_kmod_version: "{{ rpm_query.stdout }}"
        afs_openafs_kmod_release: "{{ afs_openafs_kmod_prefix }}.{{ ansible_kernel | regex_replace('-','_') }}"
    - name: "CentOS-6: Trace"
      debug:
        var: afs_openafs_kmod_version
        verbosity: 1

    - name: "CentOS-6: Trace"
      debug:
        var: afs_openafs_kmod_release
        verbosity: 1

    - name: "CentOS-6: Install OpenAFS client"
      yum:
        state: present
        name:
          - openafs-client
          - kmod-openafs-{{ afs_openafs_kmod_version }}-{{ afs_openafs_kmod_release }}
          - openafs-krb5

- name: "CentOS-6: Load kernel module"
  block:
    - name: "CentOS-6: Get kernel modules"
      command: lsmod
      check_mode: no
      changed_when: false
      register: lsmod_results

    - name: "CentOS-6: Trace lsmod output"
      debug:
        var: lsmod_results
        verbosity: 1

    - name: "CentOS-6: Load openafs kernel module"
      command: modprobe openafs
      when: not lsmod_results.stdout is search('openafs')

    - name: "CentOS-6: Get kernel modules"
      command: lsmod
      check_mode: no
      changed_when: false
      register: lsmod_results

    - name: "CentOS-6: Trace lsmod output"
      debug:
        var: lsmod_results
        verbosity: 1

    - name: "CentOS-6: Verify the OpenAFS kernel module is loaded"
      assert:
        that:
          lsmod_results.stdout is search('openafs')

- name: "CentOS-6: Set client startup options"
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  notify:
    - Restart OpenAFS client
