---
- name: "CentOS-8: Trace repo url"
  debug:
    var: afs_client_repo_url

- name: "CentOS-8: Add OpenAFS yum repo"
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_client_repo_url }}"
    gpgcheck: no

- name: "CentOS-8: DKMS mode"
  when: afs_client_install_dkms | bool
  block:
    - name: "CentOS-8: Add epel yum repo"
      become: yes
      yum:
        name: epel-release
        state: present
        update_cache: yes

    # Note: Workaround missing dkms-openafs package requires.
    - name: "CentOS-8: Install missing dkms-openafs requirements"
      yum:
        state: present
        name:
          - make
          - "kernel-devel-{{ ansible_kernel }}"

    - name: "CentOS-8: Install OpenAFS client with DKMS"
      yum:
        state: present
        name:
          - openafs
          - openafs-client
          - dkms-openafs
          - openafs-krb5
      register: yum_results

    - name: "CentOS-8: Get dkms status"
      command: dkms status
      check_mode: no
      changed_when: false
      register: dkms_status

    - debug:
        var: dkms_status
        verbosity: 1

    - name: "CentOS-8: Verify openafs dkms status is 'installed'"
      assert:
        that:
          dkms_status.stdout is regex('openafs, .* installed')

- name: "CentOS-8: kmod mode"
  when: not (afs_client_install_dkms | bool)
  block:
    - name: "CentOS-8: Install OpenAFS base package"
      yum:
        state: present
        name:
          - openafs

    - name: "CentOS-8: Query OpenAFS version"
      command: rpm -q --queryformat "%{VERSION}" openafs
      args:
        warn: False
      changed_when: False
      register: rpm_query

    - name: "CentOS-8: Set kernel module package version"
      set_fact:
        afs_openafs_kmod_version: "{{ rpm_query.stdout }}"
        afs_openafs_kmod_release: "{{ afs_openafs_kmod_prefix }}.{{ ansible_kernel | regex_replace('-','_') }}"
    - name: "CentOS-8: Trace"
      debug:
        var: afs_openafs_kmod_version
        verbosity: 1

    - name: "CentOS-8: Trace"
      debug:
        var: afs_openafs_kmod_release
        verbosity: 1

    - name: "CentOS-8: Install OpenAFS client"
      yum:
        state: present
        name:
          - openafs-client
          - kmod-openafs-{{ afs_openafs_kmod_version }}-{{ afs_openafs_kmod_release }}
          - openafs-krb5

- name: "CentOS-8: Load kernel module"
  block:
    - name: "CentOS-8: Get kernel modules"
      slurp:
        src: /proc/modules
      register: modules

    - name: "CentOS-8: Dump kernel modules"
      debug:
        msg: "{{ modules.content | b64decode }}"
        verbosity: 1

    - name: "CentOS-8: Load openafs kernel module"
      command: modprobe openafs
      when: (modules.content | b64decode) is not search('openafs')

    - name: "CentOS-8: Verify the OpenAFS kernel module is loaded"
      wait_for:
        path: /proc/modules
        search_regex: openafs
        timeout: 5

- name: "CentOS-8: Set client startup options"
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  notify:
    - Restart OpenAFS client
