---
- name: "CentOS-6: Trace repo url"
  debug:
    var: afs_client_repo_url

- name: "CentOS-6: Add OpenAFS yum repo"
  become: yes
  yum_repository:
    name: openafs
    description: OpenAFS yum repo
    baseurl: "{{ afs_client_repo_url }}"
    gpgcheck: no

- name: "CentOS-6: DKMS mode"
  when: afs_client_install_dkms | bool
  block:
    - name: "CentOS-6: Add epel yum repo"
      become: yes
      yum:
        name: epel-release
        state: present
        update_cache: yes

    # Note: Workaround missing dkms-openafs package requires.
    - name: "CentOS-6: Install missing dkms-openafs requirements"
      become: yes
      yum:
        state: present
        name:
          - make
          - "kernel-devel-{{ ansible_kernel }}"

    - name: "CentOS-6: Install OpenAFS client with DKMS"
      become: yes
      yum:
        state: present
        name:
          - openafs
          - openafs-client
          - dkms-openafs
          - openafs-krb5
      register: yum_results

    - name: "CentOS-6: Get dkms status"
      become: yes
      command: /usr/sbin/dkms status
      check_mode: no
      changed_when: false
      register: dkms_status

    - debug:
        var: dkms_status
        verbosity: 1

    - name: "CentOS-6: Verify openafs dkms status is 'installed'"
      assert:
        that:
          dkms_status.stdout is regex('openafs, .* installed')

- name: "CentOS-6: kmod mode"
  when: not (afs_client_install_dkms | bool)
  block:
    - name: "CentOS-6: Install OpenAFS base package"
      become: yes
      yum:
        state: present
        name:
          - openafs

    - name: "CentOS-6: Query OpenAFS version"
      command: rpm -q --queryformat "%{VERSION}" openafs
      args:
        warn: False
      changed_when: False
      register: rpm_query

    - name: "CentOS-6: Set kernel module package version"
      set_fact:
        afs_openafs_kmod_version: "{{ rpm_query.stdout }}"
        afs_openafs_kmod_release: "{{ afs_openafs_kmod_prefix }}.{{ ansible_kernel | regex_replace('-','_') }}"

    - name: "CentOS-6: Trace"
      debug:
        var: afs_openafs_kmod_version
        verbosity: 1

    - name: "CentOS-6: Trace"
      debug:
        var: afs_openafs_kmod_release
        verbosity: 1

    - name: "CentOS-6: Install OpenAFS client"
      become: yes
      yum:
        state: present
        name:
          - openafs-client
          - kmod-openafs-{{ afs_openafs_kmod_version }}-{{ afs_openafs_kmod_release }}
          - openafs-krb5

- name: Gather OpenAFS installation facts
  become: yes
  openafs_gather_facts:
    state: update
    pkg: rpm

- name: "CentOS-6: Load kernel module"
  block:
    - name: "CentOS-6: Get kernel modules"
      slurp:
        src: /proc/modules
      register: modules

    - name: "CentOS-6: Dump kernel modules"
      debug:
        msg: "{{ modules.content | b64decode }}"
        verbosity: 1

    - name: "CentOS-6: Load openafs kernel module"
      become: yes
      command: modprobe openafs
      when: (modules.content | b64decode) is not search('openafs')

    - name: "CentOS-6: Verify the OpenAFS kernel module is loaded"
      wait_for:
        path: /proc/modules
        search_regex: openafs
        timeout: 5

- name: "CentOS-6: Set client startup options"
  become: yes
  lineinfile:
    path: /etc/sysconfig/openafs
    regexp: "^AFSD_ARGS="
    line: 'AFSD_ARGS="{{ afs_afsd_opts }}"'
    state: present
  notify:
    - Restart OpenAFS client

- name: "CentOS-6: Set OpenAFS installation paths"
  set_fact:
    afs_afsd: /usr/sbin/afsd
    afs_fs: /usr/bin/fs
    afs_viceetcdir: /usr/vice/etc
