---
# Kerberos commands
afs_kadmin_local: "/sbin/kadmin.local"
afs_kdb5_util: "/sbin/kdb5_util"

# Kerberos files
afs_krbserver_krb5_conf: "/etc/krb5.conf"
afs_krbserver_kdc_conf: "/var/kerberos/krb5kdc/kdc.conf"
afs_krbserver_kadm5_acl: "/var/kerberos/krb5kdc/kadm5.acl"
afs_krbserver_kadm5_keytab: "/var/kerberos/krb5kdc/kadm5.keytab"
afs_krbserver_principal: "/var/kerberos/krb5kdc/principal"

# Kerberos service names
afs_krbserver_kdc_service: krb5kdc
afs_krbserver_admin_service: kadmin

# OS dependent variables
afs_firewall: firewalld
