---
- name: "Gather variables for each operating system"
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
    - "../vars/{{ ansible_distribution }}.yaml"
    - "../vars/{{ ansible_os_family }}.yaml"
    - "../vars/defaults.yaml"

- name: "Install development tools and libraries"
  include_tasks: "{{ item }}"
  with_first_found:
    - "install/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_version }}.yaml"
    - "install/{{ ansible_distribution | replace(' ', '_') }}-{{ ansible_distribution_major_version }}.yaml"
    - "install/{{ ansible_distribution | replace(' ', '_') }}.yaml"
    - "install/{{ ansible_os_family | replace(' ', '_') }}.yaml"
    - "install/unknown.yaml"
