---
- name: Remove staged server files
  file:
    path: "{{ afs_devel_destdir }}/usr/afs"
    state: absent
  when: not afs_devel_build_server

- name: Create extra directories for server files
  file:
    state: directory
    path: "{{ afs_devel_destdir }}/{{ item }}"
  with_items:
    - "{{ afs_asetkey | dirname }}"
    - "/usr/lib/systemd/system"
  when: afs_devel_build_server

- name: Create extra directories for client files
  file:
    state: directory
    path: "{{ afs_devel_destdir }}/{{ item }}"
  with_items:
    - "/etc/sysconfig"
  when: afs_devel_build_client

- name: Install asetkey to a standard location
  copy:
    remote_src: true
    src: "{{ afs_devel_builddir }}/src/aklog/asetkey"
    dest: "{{ afs_devel_destdir }}/{{ afs_asetkey }}"
    owner: root
    group: root
    mode: 0755
  when: afs_devel_build_server

- name: Check for akeyconvert availability
  stat:
    path: "{{ afs_devel_builddir }}/src/aklog/akeyconvert"
  register: akeyconvert_st

- name: Install akeyconvert to a standard location
  copy:
    remote_src: true
    src: "{{ afs_devel_builddir }}/src/aklog/akeyconvert"
    dest: "{{ afs_devel_destdir }}/{{ afs_akeyconvert }}"
    owner: root
    group: root
    mode: 0755
  when: afs_devel_build_server and akeyconvert_st.stat.exists

- name: Install module probe script
  copy:
    src: CentOS-6/openafs-client.modules
    dest: "{{ afs_devel_destdir }}/etc/sysconfig/openafs"
  when: afs_devel_build_client
