---
- name: Check for dest directory
  stat:
    path: "{{ afs_server_build_destdir }}"
  register: destdir_st
  when: not afs_server_build_force|bool

- name: Build dest directory from source
  include_role:
    name: openafs_devel
    tasks_from: build
  vars:
    afs_devel_build_server: yes
    afs_devel_build_client: no
    afs_devel_builddir: "{{ afs_server_build_builddir }}"
    afs_devel_destdir: "{{ afs_server_build_destdir }}"
    afs_devel_fetch_method: "{{ afs_server_build_fetch_method }}"
    afs_devel_git_repo: "{{ afs_server_build_git_repo }}"
    afs_devel_git_ref: "{{ afs_server_build_git_ref }}"
  when: afs_server_build_force|bool or not destdir_st.stat.exists

- name: Install dest directory to system
  command: rsync -a --info=name --checksum . /
  args:
    chdir: "{{ afs_server_build_destdir }}"
  register: rsync_results
  failed_when: rsync_results.rc != 0
  changed_when:
    - rsync_results.stdout != ''

- name: Platform specific post-install tasks
  include_tasks: "post-rsync-{{ ansible_os_family | lower }}.yaml"
  when: rsync_results.changed
